fix ansible script for pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,12 +23,20 @@ jobs:
       - name: Deploy CloudFormation Stack
         run: |
           aws cloudformation deploy --stack-name TaskManagerStack --template-file cloudformation.yaml --capabilities CAPABILITY_NAMED_IAM
+          if [ $? -ne 0 ]; then
+            echo "CloudFormation deployment failed."
+            exit 1
+          fi
 
       - name: Get EC2 Public IP
         id: ec2-info
         run: |
           public_ip=$(aws ec2 describe-instances --filters "Name=tag:aws:cloudformation:stack-name,Values=TaskManagerStack" --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
           echo "Public IP: $public_ip"
+          if [ -z "$public_ip" ]; then
+            echo "Failed to retrieve the EC2 public IP."
+            exit 1
+          fi
           echo "::set-output name=public_ip::$public_ip"
 
       - name: Set up SSH Key
@@ -36,6 +44,10 @@ jobs:
         run: |
             echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
             chmod 600 private_key.pem
+            if [ ! -f private_key.pem ]; then
+              echo "Failed to set up SSH private key."
+              exit 1
+            fi
 
       - name: Run Ansible Playbook
         env:
@@ -43,3 +55,7 @@ jobs:
         run: |
           echo "EC2 Public IP: $EC2_PUBLIC_IP"
           ansible-playbook -i $EC2_PUBLIC_IP, deploy_taskmanager.yml --private-key private_key.pem
+          if [ $? -ne 0 ]; then
+            echo "Ansible playbook execution failed."
+            exit 1
+          fi
